### ISSUE TITLE
Pillar causing existing R project to fail

### ISSUE THREAD

**Issue by Miner82** [r-lib/pillar#198]
Hi everyone;
 I woke up this morning to upload an R Markdown for a portfolio I'm building in github.      The 'Pillar' package is now missing, and tidyverse, since it uses pillar as dependency, fails.   The R code and its markdown project now fails.   
I've tried to re-install tidyverse, but it stops with 'non-zero exit' and removes itself from the download.  Looking upstream in the error stream, a package called  'lifecycle', which pillar uses, has failed.  A package called 'hms' has failed.   
Can anyone help?  I've spent months working on  some data projects to show off to recruiters via github.    And now can't run anything.    It looks like tidyverse and its lifecycle/pillar dependencies is the culprit.
I would be eternally grateful for any help or advice.

**Comment by batpigandme** [comment]
Have you tried installing lifecycle and pillar individually? That said, this sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.) If it turns out this is an issue with pillar, we can always come back and open an issue with more information. Thanks.
