### ISSUE TITLE
Control significant figures with an option

### ISSUE THREAD

**Issue by cboettig** [r-lib/pillar#72]
For instance, I see that 

> Digits after the first three are dimmed to emphasise the important components.

But you'll have to explain to me how the digits `201` are the important components of the year column in the example 😛 .  Being able to change the default behavior somehow to give me 4 digits would be nice in instances like my class where students end up reading in a lot of examples where `year` is a column.  I want them to like tibbles and not get frustrated by this unintuitive behavior.

**Comment by hadley** [comment]
The underlying problem here is #57 -  I think if we fix that an option will not be necessary.

I'd prefer to push as far as we can before introducing more options, since options substantially increase the testing complexity, and make the package behave differently for different people. If this new behaviour is too annoying, we can definitely consider options, but I'd like to give it more time (i.e. open again in 6 months time if it's still a problem and I'll be more amenable)

**Comment by hadley** [comment]
I've changed my mind - it's causing enough pain for enough people right now that we should have someway to suppress. 

Probably easiest to parameterise as `option(pillar.sigfigs = 3)` allowing `option(pillar.sigfigs = Inf)`to turn it off.

**Comment by ilarischeinin** [comment]
Unaware of this issue, I was actually already in the middle of implementing this kind of option for my own use. But then I came here to check if there was any discussion in more general terms about the question of left-hand-sides of numbers and significant digits vs. thousands separators.

As a little background, I was surprised at first when I saw that in e.g. `1234` the three digits with a separate color are `123` and not `234`. Also, I would've thought that if `123456789` was shown in two colors, `123` and `789` would be shown in one, and `456` in the other color. That is, I thought that the two colors represented thousands separators. I was therefore confused what it actually meant, and only from the documentation learned that it represented significant digits.

Since I didn't want to use it that way, I started to implement an option so I could use `options(pillar.sigfigs = Inf)`.

But then I got to thinking that would the thousands separator idea actually be a more useful use case for the colors than significant digits? Consistency is important, but since `sigfig` already means different things for the rhs (colors and rounding) and lhs (no rounding, only colors), I'm not sure if that rules out the idea.

I definitely haven't looked into this very deeply, so there might be fairly obvious factors at play that make my suggestion ridiculous. Or maybe it's just plain stupid. But since I have spent a fair amount of time staring at integers on the scale of millions (base pair numbers in the human genome), I for one see a lot of potential in this kind of representation (color formatting) of thousands separators. Use of commas, or extra characters in general, is problematic for copy&paste.

**Comment by dpeterson71** [comment]
I agree that this has to change.  The current implementation makes inspecting tibbles almost impossible for me.   I LOVE the alignment along decimal points, but the forced highlight of only three digits is confusing at best.  Not only is this unintuitive (as cboettig indicates), it is visually distracting 
 in many cases.

**Comment by krlmlr** [comment]
See #78 for a suggestion for visible thousand separators using a very light gray background every other three digits.

**Comment by ilarischeinin** [comment]
Thank you for the new options in #79!

However, I still think there should either be
- a separation in how significant figures are treated on the left and right hand sides,
- a mode that didn't force the number of significant digits to be set (like with base R), or
- a separate option that would override the formatting of lhs's (#78).

I really like having `subtle` for things like column headers or how POSIXct's are displayed. So, I would prefer not to turn it off. But if I don't turn it off, I'm forced to set `sigfig` to some value. If it's small (like 3), numbers (or their lhs's to be exact) look funny. If it's large (like 10), there are many unnecessary zeros on the rhs's (#62 is about this, but I think the functionality discussed on that issue would be a slippery slope to go down).

![screen shot 2018-01-11 at 16 15 24](https://user-images.githubusercontent.com/2540173/34829848-adb76c36-f6ea-11e7-9db2-708933fdd49f.png)

**Comment by hadley** [comment]
That is not under consideration right now. It needs more discussion, and we need to get a release out to resolve the biggest problems.

**Comment by krlmlr** [comment]
@ilarischeinin: Happy to discuss this in a separate issue or even pull request ;-)
