### ISSUE TITLE
Thousand separator with color?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#78]
@hadley: Should we add an option to use a very light gray as background every other three digits (see image)?

![screenshot from 2018-01-10 09-40-39](https://user-images.githubusercontent.com/1741643/34763169-734cb32c-f5ea-11e7-9211-ee3507a6f11b.png)

I tried [combining diacritic marks](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks), but they look inconsistent with different fonts and also appear if you copy-paste a number. Spending a whole space sounds wasteful, too.

**Comment by hadley** [comment]
I tried that in my experiments and didn't find it particularly compelling. It's hard to use a sufficiently light grey because we'd need to detect light vs dark backgrounds, and rely on 256 colour support.

**Comment by ilarischeinin** [comment]
As I mentioned in #72, I find compatibility with copy&paste to be a valuable asset. Colors are probably the least interfering option in that sense. (If given multiple options, personally I would prefer to use text color for this (instead of using it for significant digits), but that's just me.)

**Comment by dpeterson71** [comment]
Kirill's idea is interesting...sort of like the "engineering" format on many scientific calculators.  There is clearly a use for such a thing or it wouldn't be common on calculators and obviously scratches a particular itch for some users. 

I like the notion of putting this in a theme paradigm.  I doubt that I would ever use such highlighting and would immediately turn it off by default.  My brain just sees this as visual noise; my focus is drawn to the highlighting rather than the actual data and thus much more effort is required to figure out what the numbers mean.  Finally, for choosing theme/option/parameter names for such a feature, I think it would be good to keep in mind this isn't about "significant" digits, but rather about "display properties" of digits.

**Comment by krlmlr** [comment]
Support for underlining every third digit added in c3f9de2b.

**Comment by hadley** [comment]
Can we try alternating underline off and on for each 3 digit block?

**Comment by krlmlr** [comment]
Sure:

![screenshot from 2018-02-10 22-38-13](https://user-images.githubusercontent.com/1741643/36066897-2af7a686-0eb3-11e8-8c4d-c4eddc4deb91.png)

Preview for larger and smaller numbers follows.

**Comment by krlmlr** [comment]
![screenshot from 2018-02-10 22-39-34](https://user-images.githubusercontent.com/1741643/36066908-4e32f25e-0eb3-11e8-869c-09aa2566d099.png)
![screenshot from 2018-02-10 22-39-21](https://user-images.githubusercontent.com/1741643/36066909-4e4c1eb4-0eb3-11e8-8655-42432c9982c5.png)

**Comment by hadley** [comment]
Hmmm I’m not sure how I feel about it. @jimhester what do you think?

Might be easier to assess if there were more variation in the numbers? (Ie not just zero and one$

**Comment by krlmlr** [comment]
![screenshot from 2018-02-10 23-23-37](https://user-images.githubusercontent.com/1741643/36067225-7be7a3e2-0eb9-11e8-92cc-ec208da30a32.png)

![screenshot from 2018-02-10 23-24-21](https://user-images.githubusercontent.com/1741643/36067231-8f123fa4-0eb9-11e8-81e0-7e1ada9e19b6.png)

**Comment by jimhester** [comment]
I don't love it, but not sure I like any of the other options much better...

**Comment by randomgambit** [comment]
why dont you use a simple red gradient for positive numbers, and green for negative ones? Number for millions would be more red than numbers for hundreds. Something like that

**Comment by randomgambit** [comment]
here is simple example done in word (sorry guys hehe)

![image](https://user-images.githubusercontent.com/8282510/36637502-fbc5c868-19aa-11e8-8e0a-a308ac6e3958.png)

**Comment by dpeterson71** [comment]
@randomgambit: Wouldn't you use green for positive and red for negative?  "In the red" generally means negative.  Regarding your example, I really dislike the notion of a single number having read _and_ green digits.  The idea of a gradient is interesting, but I would keep all digits in the same color family.  Perhaps a symmetric gradient about the decimal point would be appropriate?

Of course, at some point this is why scientific notation was developed: to compare orders of magnitude easier and more reliably than counting digits.

**Comment by randomgambit** [comment]
yes, that was just meant as an illustrative example. 

My point is that coloring/formatting could help the user quickly parse the numbers in 100s of thousands vs 100s vs decimals, etc. Essentially I propose coloring by groups of numbers identified by which bucket their exponent **in scientific notation** would falls into: [0-2] for  0 to hundreds would be light green , [3-5] for thousands to hundreds of thousands would be a bit darker, and so on. I think that could work just fine.

Also, related is https://github.com/r-lib/pillar/issues/40#issuecomment-360152576 Please dont play with how many digits is shown without telling the user. This is a serious issue that will prevent people from using the package altogether.

In any case, thanks for your work!

**Comment by randomgambit** [comment]
in my experience I have never seen anyone keeping numbers in scientific format (in the terminal) when processing the data because its actually difficult to see what's going on. that is where block coloring (as proposed above) can play the role of adding the scientific notation logic to the full number printing

**Comment by dpeterson71** [comment]
Well our experiences are apparently different.  I work with data that often spans multiple orders of magnitude, from 10E+06 (or more) to 10E-06.  Having the full numbers printed is more than a hindrance to interpreting the results, it requires a numeric field of at least 13 characters!  For me it is far, *FAR* easier to have everything in scientific notation and simply scan the last 3 characters: +06 or -03 for example.   To reiterate my earlier comments, I think the current implementation of the coloring paradigm is more distracting than informative---it's visual noise.  My focus is taken away from the data and towards the formatting.  I find myself more often than not spending time wondering, "Why is that digit colored but this one not?" rather than the more important question, "Why is that measurement 50% greater than this one?"

I think pillar has some great promise, but it still has a long ways to go, and that's what these discussions are for.  I agree the developers are doing a good job of listening to feedback as pillar evolves, and it's certainly not an easy task. Kudos to them!

**Comment by randomgambit** [comment]
very interesting. well, i guess the right answer for both use cases is to provide the use the option to switch on/off any formatting ;)

**Comment by krlmlr** [comment]
Thanks. I don't think we should use a color gradient. We should think more about using engineering format where appropriate, and perhaps offer easy ways to tweak the output per column.

Discussions in closed issues are difficult to follow, please open new issues or comment existing open issues, preferably in tibble if it "only" concerns the display.

**Comment by brodieG** [comment]
@randomgambit @dpeterson71 you might also be interested in #96

**Comment by randomgambit** [comment]
@krlmlr got it. After playing a bit with the new release, I think the original idea (with gray shading) is actually easier to read than the underscore line.

For instance, on my high definition screen (with tiny, tiny numbers) it is difficult to see the difference between, say, 932000 and 1920333 because there is just one extra number so the line is slightly shorter
