### ISSUE TITLE
pillar not installing in R

### ISSUE THREAD

**Issue by adsaxon** [r-lib/pillar#92]
I've repeatedly tried to install pillar from the CRAN repository. It keeps sending the message there is no package called 'pillar'. Hence when trying to load ggplot2, this message appears:

Error: package or namespace load failed for ‘ggplot2’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘pillar’

**Comment by mfox9** [comment]
I just had the same issue, and installing from github using devtools worked:

`# install.packages("devtools")
devtools::install_github("r-lib/pillar")`

https://github.com/r-lib/pillar

**Comment by ajdamico** [comment]
hi, all my appveyor builds (which have a `tibble` dependency) died this morning because [the r-release is no longer available](https://cran.r-project.org/web/packages/pillar/index.html).  just want to check if the windows build will be re-sent to cran, or if this is a permanent change and i should add a `Remotes:` to my builds?  thanks!

**Comment by deanhardy** [comment]
Thanks @mfox9! After running updateR() and getting the same error about pillar, your suggestion took care of the problem for me.

**Comment by krlmlr** [comment]
pillar is a dependency of tibble, and should be installed automatically when you install tibble. I sent an updated version of pillar to CRAN yesterday, this may be the reason for the outages you're seeing.

You can always install the development version via `devtools::install_github()` or `remotes::install_github()`, and usually installation from CRAN also just works.

**Comment by ajdamico** [comment]
seems to be resolved..  earlier today, the `r-release` windows binary on the [pillar cran page](https://cran.r-project.org/web/packages/pillar/index.html) linked to https://cran.r-project.org/bin/windows/contrib/3.4/ReadMe and not the zipped file that it links to now.  thanks  :)

**Comment by krlmlr** [comment]
Thanks for the heads-up.

**Comment by antoniolamadeu** [comment]
Thank you very much "mfox9", your post is really a "fix" for this issue.!!!!

**Comment by LouGallagher** [comment]
I am running 3.5.2 and can't install pillar or broom.
I've tried the above 'fixes' but these bring more errors, as displayed here:

> devtools::install_github("r-lib/pillar")
Error in loadNamespace(name) : there is no package called ‘devtools’
> devtools::install_github("r-lib/broom")
Error in loadNamespace(name) : there is no package called ‘devtools’
> install.devtools
Error: object 'install.devtools' not found
> devtools::install_github()
Error in loadNamespace(name) : there is no package called ‘devtools’
> install.devtools
Error: object 'install.devtools' not found
> remotes::install_github()
Error in loadNamespace(name) : there is no package called ‘remotes’
>

**Comment by LouGallagher** [comment]
As to the above set of errors, I had to change the Global Options to specify the updated version of R I was using, 3.5.2  - not sure why that function doesn't happen automatically?

**Comment by batpigandme** [comment]
To install from GitHub you need to install devtools
`install.packages("devtools")`

**Comment by sanjay-singh3210** [comment]
> I just had the same issue, and installing from github using devtools worked:
> 
> `# install.packages("devtools")`
> `devtools::install_github("r-lib/pillar")`
> 
> https://github.com/r-lib/pillar

Hi, I am trying to install library dplyr which I am unable to do because pillar is not installing. I using Win10. Can you please help me how to fix it? Thanks. I am new to Github
Given below is details of error messages:
------------------------------------------

> install.packages("dplyr")
Installing package into ‘C:/Users/yagga/OneDrive/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘fansi’, ‘glue’, ‘Rcpp’, ‘rlang’, ‘tibble’, ‘tidyselect’


  There are binary versions available but the source versions are later:
            binary  source needs_compilation
fansi        0.2.2   0.4.0              TRUE
glue         1.2.0   1.3.0              TRUE
Rcpp       0.12.16   1.0.0              TRUE
rlang        0.2.0   0.3.1              TRUE
tibble       1.4.2   2.0.1              TRUE
tidyselect   0.2.4   0.2.5              TRUE
dplyr        0.7.4 0.8.0.1              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/fansi_0.2.2.zip'
Content type 'application/zip' length 141745 bytes (138 KB)
downloaded 138 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/glue_1.2.0.zip'
Content type 'application/zip' length 72364 bytes (70 KB)
downloaded 70 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/Rcpp_0.12.16.zip'
Content type 'application/zip' length 4358189 bytes (4.2 MB)
downloaded 4.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rlang_0.2.0.zip'
Content type 'application/zip' length 754726 bytes (737 KB)
downloaded 737 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/tibble_1.4.2.zip'
Content type 'application/zip' length 172305 bytes (168 KB)
downloaded 168 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/tidyselect_0.2.4.zip'
Content type 'application/zip' length 612053 bytes (597 KB)
downloaded 597 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/dplyr_0.7.4.zip'
Content type 'application/zip' length 2897358 bytes (2.8 MB)
downloaded 2.8 MB

package ‘fansi’ successfully unpacked and MD5 sums checked
package ‘glue’ successfully unpacked and MD5 sums checked
package ‘Rcpp’ successfully unpacked and MD5 sums checked
package ‘rlang’ successfully unpacked and MD5 sums checked
package ‘tibble’ successfully unpacked and MD5 sums checked
package ‘tidyselect’ successfully unpacked and MD5 sums checked
package ‘dplyr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\yagga\AppData\Local\Temp\RtmpiGM0SV\downloaded_packages
> library("dplyr")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘rlang’ 0.2.0 is already loaded, but >= 0.3.0.1 is required
Error: package or namespace load failed for ‘dplyr’
> library("pillar")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘rlang’ 0.2.0 is already loaded, but >= 0.3.0.1 is required
In addition: Warning message:
package ‘pillar’ was built under R version 3.5.2 
Error: package or namespace load failed for ‘pillar’

**Comment by sumit1011** [comment]
I am trying to use Flexsurv package which was not working becaise pillar and crayon package was not installed. I installed pillar and crayon. Not I am getting below mentioned error. Please help.
Error : package or namespace load failed for 'flexsurv' in get(Info[i, 1], envir = env): lazy-load database 'C:/RPackages/Weibull/pillar/R/pillar.rdb' is corrupt"

**Comment by krlmlr** [comment]
Thanks. Do you need to restart your R session?

In the future, can you please open a new issue? It's easy to overlook comments to closed issues.

**Comment by sumit1011** [comment]
> Thanks. Do you need to restart your R session?
> 
> In the future, can you please open a new issue? It's easy to overlook comments to closed issues.

Sorry about that I was reading through the previous comments and posted here. I tried restarting, removing package and reinstalling package. I uninstalled R completely and now will install the package in separate folder.

**Comment by GabrielaCardenasF** [comment]
> I just had the same issue, and installing from github using devtools worked:
> 
> `# install.packages("devtools")`
> `devtools::install_github("r-lib/pillar")`
> 
> https://github.com/r-lib/pillar

What if I get this mesagge after running it:
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: rlang (0.4.6 -> 0.4.7) [CRAN]

Enter one or more numbers, or an empty line to skip updates:

✓  checking for file ‘/private/var/folders/g9/f7w5z2_900lg43lcswhb6kbm0000gn/T/Rtmppkn3PC/remotes60d3a698649/r-lib-pillar-a84911e/DESCRIPTION’ ...
─  preparing ‘pillar’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘pillar_1.4.6.9000.tar.gz’
   
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 25167 Done                    echo 'tools:::.install_packages()'
     25168 Abort trap: 6           | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}
Error: Failed to install 'pillar' from GitHub:
  (converted from warning) installation of package ‘/var/folders/g9/f7w5z2_900lg43lcswhb6kbm0000gn/T//Rtmppkn3PC/file60d315ef27f6/pillar_1.4.6.9000.tar.gz’ had non-zero exit status
>
