### ISSUE TITLE
TRUE and FALSE, not T and F

### ISSUE THREAD

**Issue by jennybc** [r-lib/pillar#95]
I suggest displaying logical `TRUE` and `FALSE` as just that, vs. `T` and `F`.

I think many discourage the use of `T` and `F` in code, when we mean `TRUE` and `FALSE`, so I don't like giving the suboptimal thing so much exposure.

Also, as @hadley points out, `<lgl>` and `FALSE` are the same width, so `T` and `F` aren't actually saving any horizontal space.

**Comment by mentalplex** [comment]
I agree that `TRUE` and `FALSE` are generally better, but disagree that `T` and `F` are not saving any horizontal space. By choosing `T` and `F`, you're not saving horizontal space in the required width of the column, but you are saving horizontal whitespace between column values.

**Comment by hadley** [comment]
@mentalplex I don't get it — `<lgl>` also gets a space after it.

**Comment by mentalplex** [comment]
@hadley 

We're using different terms here, so I may have described this in a silly way, but my point is that you do get (white)space by abbreviating.

```
toy <- data.frame(x = rnorm(6), y = sample(c(TRUE, FALSE), 6, replace = TRUE), z = runif(6))
print(toy, digits = 3)
as.tibble(toy)
```

There is more horizontal (white)space when `FALSE` is abbreviated to `F`.  But it is only in the rows. It's still space, though. And it may make it easier to see the data. I'm not arguing that it's better one way or the other.

**Comment by hadley** [comment]
I don't think that whitespace is useful.

**Comment by mentalplex** [comment]
You might be right. Just know there's a whole literature on layout and objective reading performance (reading speed, comprehension). The peer reviewed work is generally old (1960s and earlier) and about print, but there are dissertations out there that support the findings in electronic media. Generally, whitespace correlates with objective measures of reading speed, scanning and finding speed. Miles Tinker, who was probably the most prolific researcher in this field, has a principle for this case: in tables, you should abbreviate when it's unambiguous. It's been a long while since I read him, but I do remember the principle, which is why this issue caught my eye.

**Comment by hadley** [comment]
I'd argue that the full forms are easier to scan because there's a difference in the amount of whitespace, and T vs F are fairly visually confusable.

**Comment by mentalplex** [comment]
That's a good argument.

**Comment by atusy** [comment]
What about gray out ALSE after F and RUE after T?
